import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ width: "100vw", height: "100vh", backgroundColor: "#fff" }}
      >
        <nav>
          <Link href="/">Home</Link> &nbsp; &nbsp;
          <Link href="/posts">Post</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
